# Generated by Django 3.1 on 2020-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=models.CharField(max_length=100),
        ),
    ]
